apiVersion: v1
entries:
  chart-1:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-19T09:13:52.63056991Z"
    description: A Helm chart for Kubernetes
    digest: 5424a962836324316eb9e54e573b01c9b1b82e41ea3f9b5da79714517084fbe7
    name: chart-1
    type: application
    urls:
    - https://aweris.github.io/gha/dev/charts/chart-1-0.1.0.tgz
    version: 0.1.0
  chart-2:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-10-19T09:13:52.631627119Z"
    description: A Helm chart for Kubernetes
    digest: 2d6f079bf322ae564728304c60e2a80fd82e02aaac616b21736e7b503685b3da
    name: chart-2
    type: application
    urls:
    - https://aweris.github.io/gha/dev/charts/chart-2-0.1.0.tgz
    version: 0.1.0
generated: "2022-10-19T09:13:52.629322999Z"
